[package]
name = "dks3_config"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@fastmail.com>"]
edition = "2018"

[features]
default = ["client", "server"]
client = []
server = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.9"
hex-literal = "0.3.1"
rsa = { git = "https://github.com/RustCrypto/RSA" , features = ["pem", "serde"] }
serde_derive = "1.0"
serde = "1.0"
thiserror = "1.0"
toml = "0.5"