[package]
name = "dks3_server"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@fastmail.com>"]
edition = "2018"

[[bin]]
name = "dks3_server_genrsa"
path = "src/tools/genrsa.rs"

[dependencies]
config = "0.10"
fern = "0.5"
futures = "0.3"
log = "0.4"
rand = "0.7"
rsa = { git = "https://github.com/RustCrypto/RSA" , features = ["pem"] }
serde_derive = "1.0"
serde = "1.0"
tracing-futures = "0.2.3"
tracing-subscriber = "0.2.2"

[dependencies.dks3_proto]
path = "../dks3_proto"

[dependencies.tokio]
version = "0.2"
features = ["full"]

[dependencies.tokio-util]
version = "0.3"
features = ["codec"]

[dependencies.tracing]
version = "0.1"
features = ["log"]