// This file is generated by rust-protobuf 2.17.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `Frpg2RequestMessage.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_17_0;

#[derive(PartialEq,Clone,Default,Debug)]
pub struct GetServiceStatus {
    // message fields
    f1: ::std::option::Option<i32>,
    f2: ::protobuf::SingularField<::std::string::String>,
    steam_id: ::protobuf::SingularField<::std::string::String>,
    f4: ::std::option::Option<u64>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a GetServiceStatus {
    fn default() -> &'a GetServiceStatus {
        <GetServiceStatus as ::protobuf::Message>::default_instance()
    }
}

impl GetServiceStatus {
    pub fn new() -> GetServiceStatus {
        ::std::default::Default::default()
    }

    // required int32 f1 = 1;


    pub fn get_f1(&self) -> i32 {
        self.f1.unwrap_or(0)
    }
    pub fn clear_f1(&mut self) {
        self.f1 = ::std::option::Option::None;
    }

    pub fn has_f1(&self) -> bool {
        self.f1.is_some()
    }

    // Param is passed by value, moved
    pub fn set_f1(&mut self, v: i32) {
        self.f1 = ::std::option::Option::Some(v);
    }

    // optional string f2 = 2;


    pub fn get_f2(&self) -> &str {
        match self.f2.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_f2(&mut self) {
        self.f2.clear();
    }

    pub fn has_f2(&self) -> bool {
        self.f2.is_some()
    }

    // Param is passed by value, moved
    pub fn set_f2(&mut self, v: ::std::string::String) {
        self.f2 = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_f2(&mut self) -> &mut ::std::string::String {
        if self.f2.is_none() {
            self.f2.set_default();
        }
        self.f2.as_mut().unwrap()
    }

    // Take field
    pub fn take_f2(&mut self) -> ::std::string::String {
        self.f2.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // required string steam_id = 3;


    pub fn get_steam_id(&self) -> &str {
        match self.steam_id.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_steam_id(&mut self) {
        self.steam_id.clear();
    }

    pub fn has_steam_id(&self) -> bool {
        self.steam_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_steam_id(&mut self, v: ::std::string::String) {
        self.steam_id = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_steam_id(&mut self) -> &mut ::std::string::String {
        if self.steam_id.is_none() {
            self.steam_id.set_default();
        }
        self.steam_id.as_mut().unwrap()
    }

    // Take field
    pub fn take_steam_id(&mut self) -> ::std::string::String {
        self.steam_id.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // required uint64 f4 = 4;


    pub fn get_f4(&self) -> u64 {
        self.f4.unwrap_or(0)
    }
    pub fn clear_f4(&mut self) {
        self.f4 = ::std::option::Option::None;
    }

    pub fn has_f4(&self) -> bool {
        self.f4.is_some()
    }

    // Param is passed by value, moved
    pub fn set_f4(&mut self, v: u64) {
        self.f4 = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for GetServiceStatus {
    fn is_initialized(&self) -> bool {
        if self.f1.is_none() {
            return false;
        }
        if self.steam_id.is_none() {
            return false;
        }
        if self.f4.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.f1 = ::std::option::Option::Some(tmp);
                },
                2 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.f2)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.steam_id)?;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.f4 = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.f1 {
            my_size += ::protobuf::rt::value_size(1, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.f2.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(ref v) = self.steam_id.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        if let Some(v) = self.f4 {
            my_size += ::protobuf::rt::value_size(4, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.f1 {
            os.write_int32(1, v)?;
        }
        if let Some(ref v) = self.f2.as_ref() {
            os.write_string(2, &v)?;
        }
        if let Some(ref v) = self.steam_id.as_ref() {
            os.write_string(3, &v)?;
        }
        if let Some(v) = self.f4 {
            os.write_uint64(4, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> GetServiceStatus {
        GetServiceStatus::new()
    }

    fn default_instance() -> &'static GetServiceStatus {
        static instance: ::protobuf::rt::LazyV2<GetServiceStatus> = ::protobuf::rt::LazyV2::INIT;
        instance.get(GetServiceStatus::new)
    }
}

impl ::protobuf::Clear for GetServiceStatus {
    fn clear(&mut self) {
        self.f1 = ::std::option::Option::None;
        self.f2.clear();
        self.steam_id.clear();
        self.f4 = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::protobuf::reflect::ProtobufValue for GetServiceStatus {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default,Debug)]
pub struct RequestQueryLoginServerInfo {
    // message fields
    steam_id: ::protobuf::SingularField<::std::string::String>,
    f2: ::protobuf::SingularField<::std::string::String>,
    f3: ::std::option::Option<u64>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RequestQueryLoginServerInfo {
    fn default() -> &'a RequestQueryLoginServerInfo {
        <RequestQueryLoginServerInfo as ::protobuf::Message>::default_instance()
    }
}

impl RequestQueryLoginServerInfo {
    pub fn new() -> RequestQueryLoginServerInfo {
        ::std::default::Default::default()
    }

    // required string steam_id = 1;


    pub fn get_steam_id(&self) -> &str {
        match self.steam_id.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_steam_id(&mut self) {
        self.steam_id.clear();
    }

    pub fn has_steam_id(&self) -> bool {
        self.steam_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_steam_id(&mut self, v: ::std::string::String) {
        self.steam_id = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_steam_id(&mut self) -> &mut ::std::string::String {
        if self.steam_id.is_none() {
            self.steam_id.set_default();
        }
        self.steam_id.as_mut().unwrap()
    }

    // Take field
    pub fn take_steam_id(&mut self) -> ::std::string::String {
        self.steam_id.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string f2 = 2;


    pub fn get_f2(&self) -> &str {
        match self.f2.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_f2(&mut self) {
        self.f2.clear();
    }

    pub fn has_f2(&self) -> bool {
        self.f2.is_some()
    }

    // Param is passed by value, moved
    pub fn set_f2(&mut self, v: ::std::string::String) {
        self.f2 = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_f2(&mut self) -> &mut ::std::string::String {
        if self.f2.is_none() {
            self.f2.set_default();
        }
        self.f2.as_mut().unwrap()
    }

    // Take field
    pub fn take_f2(&mut self) -> ::std::string::String {
        self.f2.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // required uint64 f3 = 3;


    pub fn get_f3(&self) -> u64 {
        self.f3.unwrap_or(0)
    }
    pub fn clear_f3(&mut self) {
        self.f3 = ::std::option::Option::None;
    }

    pub fn has_f3(&self) -> bool {
        self.f3.is_some()
    }

    // Param is passed by value, moved
    pub fn set_f3(&mut self, v: u64) {
        self.f3 = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for RequestQueryLoginServerInfo {
    fn is_initialized(&self) -> bool {
        if self.steam_id.is_none() {
            return false;
        }
        if self.f3.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.steam_id)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.f2)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.f3 = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.steam_id.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(ref v) = self.f2.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.f3 {
            my_size += ::protobuf::rt::value_size(3, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.steam_id.as_ref() {
            os.write_string(1, &v)?;
        }
        if let Some(ref v) = self.f2.as_ref() {
            os.write_string(2, &v)?;
        }
        if let Some(v) = self.f3 {
            os.write_uint64(3, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RequestQueryLoginServerInfo {
        RequestQueryLoginServerInfo::new()
    }

    fn default_instance() -> &'static RequestQueryLoginServerInfo {
        static instance: ::protobuf::rt::LazyV2<RequestQueryLoginServerInfo> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RequestQueryLoginServerInfo::new)
    }
}

impl ::protobuf::Clear for RequestQueryLoginServerInfo {
    fn clear(&mut self) {
        self.steam_id.clear();
        self.f2.clear();
        self.f3 = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::protobuf::reflect::ProtobufValue for RequestQueryLoginServerInfo {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default,Debug)]
pub struct RequestGetAnnounceMessageListResponse {
    // message fields
    pub data_list: ::protobuf::SingularPtrField<AnnounceMessageDataList>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RequestGetAnnounceMessageListResponse {
    fn default() -> &'a RequestGetAnnounceMessageListResponse {
        <RequestGetAnnounceMessageListResponse as ::protobuf::Message>::default_instance()
    }
}

impl RequestGetAnnounceMessageListResponse {
    pub fn new() -> RequestGetAnnounceMessageListResponse {
        ::std::default::Default::default()
    }

    // required .AnnounceMessageDataList data_list = 1;


    pub fn get_data_list(&self) -> &AnnounceMessageDataList {
        self.data_list.as_ref().unwrap_or_else(|| <AnnounceMessageDataList as ::protobuf::Message>::default_instance())
    }
    pub fn clear_data_list(&mut self) {
        self.data_list.clear();
    }

    pub fn has_data_list(&self) -> bool {
        self.data_list.is_some()
    }

    // Param is passed by value, moved
    pub fn set_data_list(&mut self, v: AnnounceMessageDataList) {
        self.data_list = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data_list(&mut self) -> &mut AnnounceMessageDataList {
        if self.data_list.is_none() {
            self.data_list.set_default();
        }
        self.data_list.as_mut().unwrap()
    }

    // Take field
    pub fn take_data_list(&mut self) -> AnnounceMessageDataList {
        self.data_list.take().unwrap_or_else(|| AnnounceMessageDataList::new())
    }
}

impl ::protobuf::Message for RequestGetAnnounceMessageListResponse {
    fn is_initialized(&self) -> bool {
        if self.data_list.is_none() {
            return false;
        }
        for v in &self.data_list {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.data_list)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.data_list.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.data_list.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RequestGetAnnounceMessageListResponse {
        RequestGetAnnounceMessageListResponse::new()
    }

    fn default_instance() -> &'static RequestGetAnnounceMessageListResponse {
        static instance: ::protobuf::rt::LazyV2<RequestGetAnnounceMessageListResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RequestGetAnnounceMessageListResponse::new)
    }
}

impl ::protobuf::Clear for RequestGetAnnounceMessageListResponse {
    fn clear(&mut self) {
        self.data_list.clear();
        self.unknown_fields.clear();
    }
}

impl ::protobuf::reflect::ProtobufValue for RequestGetAnnounceMessageListResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default,Debug)]
pub struct AnnounceMessageDataList {
    // message fields
    pub items: ::protobuf::RepeatedField<AnnounceMessageData>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AnnounceMessageDataList {
    fn default() -> &'a AnnounceMessageDataList {
        <AnnounceMessageDataList as ::protobuf::Message>::default_instance()
    }
}

impl AnnounceMessageDataList {
    pub fn new() -> AnnounceMessageDataList {
        ::std::default::Default::default()
    }

    // repeated .AnnounceMessageData items = 1;


    pub fn get_items(&self) -> &[AnnounceMessageData] {
        &self.items
    }
    pub fn clear_items(&mut self) {
        self.items.clear();
    }

    // Param is passed by value, moved
    pub fn set_items(&mut self, v: ::protobuf::RepeatedField<AnnounceMessageData>) {
        self.items = v;
    }

    // Mutable pointer to the field.
    pub fn mut_items(&mut self) -> &mut ::protobuf::RepeatedField<AnnounceMessageData> {
        &mut self.items
    }

    // Take field
    pub fn take_items(&mut self) -> ::protobuf::RepeatedField<AnnounceMessageData> {
        ::std::mem::replace(&mut self.items, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for AnnounceMessageDataList {
    fn is_initialized(&self) -> bool {
        for v in &self.items {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.items)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.items {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.items {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AnnounceMessageDataList {
        AnnounceMessageDataList::new()
    }

    fn default_instance() -> &'static AnnounceMessageDataList {
        static instance: ::protobuf::rt::LazyV2<AnnounceMessageDataList> = ::protobuf::rt::LazyV2::INIT;
        instance.get(AnnounceMessageDataList::new)
    }
}

impl ::protobuf::Clear for AnnounceMessageDataList {
    fn clear(&mut self) {
        self.items.clear();
        self.unknown_fields.clear();
    }
}

impl ::protobuf::reflect::ProtobufValue for AnnounceMessageDataList {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default,Debug)]
pub struct AnnounceMessageData {
    // message fields
    unk01: ::std::option::Option<u32>,
    unk02: ::std::option::Option<u32>,
    unk03: ::std::option::Option<u32>,
    header: ::protobuf::SingularField<::std::string::String>,
    message: ::protobuf::SingularField<::std::string::String>,
    pub date_time: ::protobuf::SingularPtrField<super::common::DateTime>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AnnounceMessageData {
    fn default() -> &'a AnnounceMessageData {
        <AnnounceMessageData as ::protobuf::Message>::default_instance()
    }
}

impl AnnounceMessageData {
    pub fn new() -> AnnounceMessageData {
        ::std::default::Default::default()
    }

    // required uint32 unk01 = 1;


    pub fn get_unk01(&self) -> u32 {
        self.unk01.unwrap_or(0)
    }
    pub fn clear_unk01(&mut self) {
        self.unk01 = ::std::option::Option::None;
    }

    pub fn has_unk01(&self) -> bool {
        self.unk01.is_some()
    }

    // Param is passed by value, moved
    pub fn set_unk01(&mut self, v: u32) {
        self.unk01 = ::std::option::Option::Some(v);
    }

    // required uint32 unk02 = 2;


    pub fn get_unk02(&self) -> u32 {
        self.unk02.unwrap_or(0)
    }
    pub fn clear_unk02(&mut self) {
        self.unk02 = ::std::option::Option::None;
    }

    pub fn has_unk02(&self) -> bool {
        self.unk02.is_some()
    }

    // Param is passed by value, moved
    pub fn set_unk02(&mut self, v: u32) {
        self.unk02 = ::std::option::Option::Some(v);
    }

    // required uint32 unk03 = 3;


    pub fn get_unk03(&self) -> u32 {
        self.unk03.unwrap_or(0)
    }
    pub fn clear_unk03(&mut self) {
        self.unk03 = ::std::option::Option::None;
    }

    pub fn has_unk03(&self) -> bool {
        self.unk03.is_some()
    }

    // Param is passed by value, moved
    pub fn set_unk03(&mut self, v: u32) {
        self.unk03 = ::std::option::Option::Some(v);
    }

    // required string header = 4;


    pub fn get_header(&self) -> &str {
        match self.header.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_header(&mut self) {
        self.header.clear();
    }

    pub fn has_header(&self) -> bool {
        self.header.is_some()
    }

    // Param is passed by value, moved
    pub fn set_header(&mut self, v: ::std::string::String) {
        self.header = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_header(&mut self) -> &mut ::std::string::String {
        if self.header.is_none() {
            self.header.set_default();
        }
        self.header.as_mut().unwrap()
    }

    // Take field
    pub fn take_header(&mut self) -> ::std::string::String {
        self.header.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // required string message = 5;


    pub fn get_message(&self) -> &str {
        match self.message.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_message(&mut self) {
        self.message.clear();
    }

    pub fn has_message(&self) -> bool {
        self.message.is_some()
    }

    // Param is passed by value, moved
    pub fn set_message(&mut self, v: ::std::string::String) {
        self.message = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_message(&mut self) -> &mut ::std::string::String {
        if self.message.is_none() {
            self.message.set_default();
        }
        self.message.as_mut().unwrap()
    }

    // Take field
    pub fn take_message(&mut self) -> ::std::string::String {
        self.message.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // required .DateTime date_time = 6;


    pub fn get_date_time(&self) -> &super::common::DateTime {
        self.date_time.as_ref().unwrap_or_else(|| <super::common::DateTime as ::protobuf::Message>::default_instance())
    }
    pub fn clear_date_time(&mut self) {
        self.date_time.clear();
    }

    pub fn has_date_time(&self) -> bool {
        self.date_time.is_some()
    }

    // Param is passed by value, moved
    pub fn set_date_time(&mut self, v: super::common::DateTime) {
        self.date_time = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_date_time(&mut self) -> &mut super::common::DateTime {
        if self.date_time.is_none() {
            self.date_time.set_default();
        }
        self.date_time.as_mut().unwrap()
    }

    // Take field
    pub fn take_date_time(&mut self) -> super::common::DateTime {
        self.date_time.take().unwrap_or_else(|| super::common::DateTime::new())
    }
}

impl ::protobuf::Message for AnnounceMessageData {
    fn is_initialized(&self) -> bool {
        if self.unk01.is_none() {
            return false;
        }
        if self.unk02.is_none() {
            return false;
        }
        if self.unk03.is_none() {
            return false;
        }
        if self.header.is_none() {
            return false;
        }
        if self.message.is_none() {
            return false;
        }
        if self.date_time.is_none() {
            return false;
        }
        for v in &self.date_time {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.unk01 = ::std::option::Option::Some(tmp);
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.unk02 = ::std::option::Option::Some(tmp);
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.unk03 = ::std::option::Option::Some(tmp);
                },
                4 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.header)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.message)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.date_time)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.unk01 {
            my_size += ::protobuf::rt::value_size(1, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.unk02 {
            my_size += ::protobuf::rt::value_size(2, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.unk03 {
            my_size += ::protobuf::rt::value_size(3, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.header.as_ref() {
            my_size += ::protobuf::rt::string_size(4, &v);
        }
        if let Some(ref v) = self.message.as_ref() {
            my_size += ::protobuf::rt::string_size(5, &v);
        }
        if let Some(ref v) = self.date_time.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.unk01 {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.unk02 {
            os.write_uint32(2, v)?;
        }
        if let Some(v) = self.unk03 {
            os.write_uint32(3, v)?;
        }
        if let Some(ref v) = self.header.as_ref() {
            os.write_string(4, &v)?;
        }
        if let Some(ref v) = self.message.as_ref() {
            os.write_string(5, &v)?;
        }
        if let Some(ref v) = self.date_time.as_ref() {
            os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AnnounceMessageData {
        AnnounceMessageData::new()
    }

    fn default_instance() -> &'static AnnounceMessageData {
        static instance: ::protobuf::rt::LazyV2<AnnounceMessageData> = ::protobuf::rt::LazyV2::INIT;
        instance.get(AnnounceMessageData::new)
    }
}

impl ::protobuf::Clear for AnnounceMessageData {
    fn clear(&mut self) {
        self.unk01 = ::std::option::Option::None;
        self.unk02 = ::std::option::Option::None;
        self.unk03 = ::std::option::Option::None;
        self.header.clear();
        self.message.clear();
        self.date_time.clear();
        self.unknown_fields.clear();
    }
}

impl ::protobuf::reflect::ProtobufValue for AnnounceMessageData {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}
