[package]
name = "cwc"
version = "0.1.0"
authors = ["Gary Tierney <gary.tierney@fastmail.com>"]
edition = "2018"

[features]
default = ["aes-mode"]
aes-mode = ["aes"]
from-software = []

[dependencies]
aes = { version = "0.5.0", optional = true }
aead = "0.3"
block-cipher = "0.8"
crypto-mac = "0.9"
generic-array = "0.14"
hex = "0.4"
subtle = "2.2"
typenum = "1.12"

[dev-dependencies]
criterion = "0.3"
criterion-cycles-per-byte = "0.1"
hex-literal = "0.3"

[[bench]]
name = "mac"
harness = false